[TASK] Do CSS Exercise
st-hanguyen/FE-Internship-Winter-2021_Ha-Nguyen_FE-Exercise pull request #6
Opened 2021-10-18 07:36 UTC by st-hanguyen

### References
- [Design URL](https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=0%3A1)
- [Issue URL](https://github.com/st-hanguyen/FE-Internship-Winter-2021_Ha-Nguyen_FE-Exercise/issues)
### Description
- [x] Tạo file style.css và dựng stylecho trang.e of Eshop: https://www.figma.com/file/CUQiZbPKOlfjHZn9hBqrPh/Fashion?node-id=8%3A194

2021-10-19 07:38 UTC, st-duynguyen commented on index.html
> +        <li class="option-item"">
dư 1 dấu ", e check lại cho tất cả những thằng ở dưới lun

2021-10-19 07:44 UTC, st-duynguyen commented on index.html
> +    <section class="section section-collection">
Thằng này a đang không thấy giống với design
![Screen Shot 2021-10-19 at 2 44 16 PM](https://user-images.githubusercontent.com/62866904/137865636-972322d5-cc54-4e6c-8fbd-dc43457910f5.png)

2021-10-19 07:46 UTC, st-duynguyen commented on index.html
> +          <h3>Selected just for you</h3>
Chỗ này cũng vậy, css a k thấy giống với design
![Screen Shot 2021-10-19 at 2 46 05 PM](https://user-images.githubusercontent.com/62866904/137865901-4dea0556-7e52-477e-bc7e-9937d0128bed.png)

2021-10-19 07:52 UTC, st-duynguyen commented on index.html
> +          <h3 class="title center">Products in today</h3>
Chỉnh font weight lại cho giống design giúp a

2021-10-19 07:53 UTC, st-duynguyen commented on index.html
> +              <!-- <span class="badge">-30%</span> -->
Chỗ này Title và giá cũng đang bị sai
![Screen Shot 2021-10-19 at 2 53 12 PM](https://user-images.githubusercontent.com/62866904/137867076-11f33703-bdef-4c09-8ba3-99f679e5c30c.png)

2021-10-19 16:02 UTC, st-duynguyen commented on index.html
> +    <div class="container footer">
chia lại theo cấu trúc
div.container 
    div.row
        div.col-6
            div.left-footer

2021-10-19 17:01 UTC, st-trangnguyen commented on assets/css/style.css
> +.container {
Em check tn này cho phần container https://supremetechhq.slack.com/archives/C02GVPHMB63/p1634568399037400

2021-10-19 17:09 UTC, st-trangnguyen commented on assets/css/style.css
> +  background-color: #ff0000;
Màu sắc của badge em tạo thêm class cho các loại badge nhé/
xem ví dụ ở đây:
https://getbootstrap.com/docs/4.0/components/badge/

2021-10-19 17:13 UTC, st-trangnguyen commented on assets/css/style.css
> +.btn-light {
- .btn.btn-light => tương tự với cái dưới
- padding 2 cái bằng nhau là 14px 20px => move lên style chung cho .btn
- line-height = nhau move lên .btn

2021-10-19 17:13 UTC, st-trangnguyen commented on assets/css/style.css
> +.item-image {
ko có css gì thì xoá đi em

2021-10-19 17:14 UTC, st-trangnguyen commented on assets/css/style.css
> +  margin-left: -10px;
sao margin mỗi left ko vậy em

2021-10-19 17:15 UTC, st-trangnguyen commented on assets/css/style.css
> +.row > * {
```
.row [class*="col-"] {
  //
}
```
dùng như vậy dễ hiểu hơn nè bé. ko cần set width mới max-width làm gì em

2021-10-19 17:17 UTC, st-trangnguyen commented on assets/css/style.css
> +  flex-direction: row;
display: flex thì direction default là row rồi em

2021-10-19 17:18 UTC, st-trangnguyen commented on assets/css/style.css
> +  left: 10%;
cần chi left 10% hè? left 0 mới đúng

2021-10-19 17:18 UTC, st-trangnguyen commented on assets/css/style.css
> +  padding-top: 6px;
dùng align-items center cho header, ko cần padding em

2021-10-19 17:19 UTC, st-trangnguyen commented on assets/css/style.css
> +  width: 75%;
nên dùng col hơn lí hơn

2021-10-19 17:21 UTC, st-trangnguyen commented on assets/css/style.css
> +  margin-top: 12px;
dùng align-items center cho header ko cần set margin bottom top gì cả, em check lun cho cái list option

2021-10-19 17:22 UTC, st-trangnguyen commented on assets/css/style.css
> +  padding-top: 0;
cần gì padding-top vậy em hè

2021-10-19 17:22 UTC, st-trangnguyen commented on assets/css/style.css
> +  top: 0px;
ko cần set top khi nó ko dịch chuyển

2021-10-19 17:23 UTC, st-trangnguyen commented on assets/css/style.css
> +  flex-direction: row;
flex default là direction row rồi

2021-10-19 17:24 UTC, st-trangnguyen commented on assets/css/style.css
> +.benefit-item .description {
chớ chị thấy css cho description ở common trên rồi mà

2021-10-19 17:25 UTC, st-trangnguyen commented on assets/css/style.css
> +  padding: 12px;
dùng flex center đi em, ko cần padding nữa

2021-10-19 17:27 UTC, st-trangnguyen commented on assets/css/style.css
> +.list-item .item-image{
space phía trc `{` em

2021-10-19 17:28 UTC, st-trangnguyen commented on assets/css/style.css
> +  filter: brightness(70%);
brightness ko support full browser ko dùng đc em

2021-10-19 17:28 UTC, st-trangnguyen commented on assets/css/style.css
> +.list-item .badge {
dùng absolute ok

2021-10-19 17:30 UTC, st-trangnguyen commented on assets/css/style.css
> +  position: absolute;
oh my got absolute chi cô nương. dùng flex cho title và button này, bọc lại 1 div rồi flex space between

2021-10-19 17:30 UTC, st-trangnguyen commented on assets/css/style.css
> +.list-item {
list-item ko có nghĩa rõ ràng ở đây, nên đổi class sang collection-item

2021-10-19 17:31 UTC, st-trangnguyen commented on assets/css/style.css
> +  top: 0px;
ko cần set top ở đây em

2021-10-19 17:31 UTC, st-trangnguyen commented on assets/css/style.css
> +  padding-top: 0;
set padding làm gì đâu em

2021-10-21 07:45 UTC, st-trangnguyen requested changes

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +              <img class="item-icon" src=" ./assets/images/noun_Search_2102816.png" alt="search">
Bị dư space phía sau `src="`. Em check lun những chỗ khác

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +            <a class=" option-link" href="#">
Bị dư space phía sau `class="`. Em check lun những chỗ khác

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +  <section class="section banner">
Banner này nằm trong phân `main`
Layout đúng của 1 page là `header` - `main` - `footer` chứ ko phải `header` - `section` - `main` - `footer`

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +            <div class="collection-card">
Em check indent của block collection-card ni nghe, đang ko đúng, những cái phía dưới cũng vậy

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +        <div class="flex section-title">
Nếu có đặt class `section-title` để style rồi thì em dùng class này style flex box nhé.
Class helper flexbox như `flex` chỉ dùng cho những div wrapper layout, ko có style gì đặt biệt khác

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +          <a href="#" class="btn btn-light">SHOW MORE</a>
btn-light => btn-secondary

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
>                <h6 class="item-name">T-Shirt Summer Vibes</h6>
Em cần chú ý thêm về cách dùng thẻ heading trong 1 page:
- Text có chứa tên brand sẽ dùng h1 và 1 trang sẽ chỉ có duy nhất 1 thẻ h1
- Text ở banner điểm nhấn sẽ là h2
- Text ở các section title sẽ là h3
- Text ở các title của list item sẽ là h4
-Ở các nơi ít quan trọng hơn sẽ dùng h5/h6

ở đây ko dùng h6 đc

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +              <span class="item-price-discount">$89.99</span>
có nên bọc 2 span price lại để cho nó flex ko? nếu có thì những chỗ khác lun

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +            <form class="form newsletter-form flex flex-item-align">
Tương tự comment cho những phần trên em ko dùng `flex flex-item-align` ở đây đc

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +    <div class="container footer ">
Dư space trong class

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +        <p class="description">House My Brand designs clothing for the young, the old &everyone in between – but most
ko đc xún hàng cho thẻ p này

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +        <ul class="row list-social">
Em dùng row ở đây làm gì khi ko li ko dùng col bé?

2021-10-21 07:45 UTC, st-trangnguyen commented on index.html
> +        <li class="col col-4">
Em cần bọc thêm 1 div row cho những li này

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +  border-top: 1px solid #ffffff;
border top ko phải của description mà là của div bọc description

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.link {
Em add nested thêm class cha vào. `link` là là 1 tên chung chung nên em sửa lại class chi tiết hơn, chị đang ko bik đây là link của cái gì

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.group-item {
Em add nested thêm class cha vào. em sửa lại class chi tiết hơn, chị đang ko bik đây là group-item của cái gì

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.list-group {
Em add nested thêm class cha vào. em sửa lại class chi tiết hơn, chị đang ko bik đây là lis-group của cái gì

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.list-item .item-icon {
Em add nested thêm class cha vào chị đang ko bik đây là list-item của cái gì

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.section-newsletter .row {
ko dùng class `row` để css lại

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.section-newsletter {
- `background-blend-mode` ko support full browser nên em dùng after như banner
- em tìm hiểu mà dùng syntax shorthand để gọn code, tối ưu code
https://www.w3schools.com/css/css_background_shorthand.asp

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +  padding: 12px;
padding nên gom nhóm với margin

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.list-product .product-item .item-price {
Mây cái price đang bị trùng css dưới, em tối ưu lại
```
font-weight: 400;
font-size: 20px;
line-height: 30px;
```

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.section-title .center {
Em tạo class tên là `text-center` có style text-align: center 
https://getbootstrap.com/docs/4.0/utilities/text/

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +.section-product .flex {
ko dùng `flex` để custom css

2021-10-21 07:45 UTC, st-trangnguyen commented on assets/css/style.css
> +  width: 56px;
chị nghĩ mấy cái bagde có width height là giống nhau, nên ko cần add thêm ở đây, và padding-top để làm gì thế em?

2021-10-21 16:06 UTC, st-trangnguyen approved these changes

2021-10-21 16:07 UTC, merged